---
title: "TidyTemplate"
date: 2020-09-22
output: html_output
editor_options: 
  chunk_output_type: console
---

# TidyTuesday

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE, 
                      warning = FALSE, message = FALSE,
                      dpi = 180, fig.width = 8, fig.height = 5)

library(tidyverse)
library(tidytuesdayR)
library(scales)
theme_set(theme_light())
```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

### Reading and Cleaning
```{r Load}
maryland_bridges <-
    read_csv(
        "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-27/baltimore_bridges.csv"
    ) %>%
    select(-vehicles) %>%
    mutate(inspection_yr = inspection_yr + 2000,
           decade_built = 10*(yr_built%/%10),
           responsibility = fct_lump(responsibility, 4),
           traffic_category = cut(avg_daily_traffic, c(0,1000,10000, Inf),
                                labels = c("< 1,000", "1,000-10,000", " > 10,000")),
           county = str_to_title(county))
```

# Exploration
```{r}
maryland_bridges %>% 
    count(decade_built) %>% 
    filter(decade_built >= 1870) %>% 
    ggplot(aes(decade_built, n)) +
    geom_line(size =1)
```


```{r}
maryland_bridges %>% 
    count(yr_built, bridge_condition) %>% 
    filter(yr_built >= 1870) %>% 
    ggplot(aes(yr_built, n, color = bridge_condition)) +
    geom_point(size =2)
```

```{r}
maryland_bridges %>% 
    filter(yr_built >= 1900) %>% 
    group_by(decade_built) %>% 
    summarise(pct_good = mean(bridge_condition == "Good"),
              total = n()) %>% 
    ggplot(aes(decade_built, pct_good)) +
    geom_line(size = 1)
```

```{r}
maryland_bridges %>% 
    count(responsibility = fct_lump(responsibility,5), sort = T) %>% 
    filter(!is.na(responsibility)) %>% 
    mutate(responsibility = fct_reorder(responsibility,n)) %>% 
    ggplot(aes(responsibility, n)) +
    geom_col() +
    coord_flip()
```

```{r}
maryland_bridges %>% 
  mutate(responsibility = replace_na(responsibility, "Other")) %>% 
  filter(yr_built >= 1900) %>% 
  mutate(
         decade = 10*yr_built%/%10) %>% 
  group_by(decade, responsibility) %>% 
  summarise(total = n(),
            pct_good = mean(bridge_condition == "Good")) %>% 
  ungroup() %>% 
  ggplot(aes(decade, pct_good, color = responsibility)) +
  geom_line(size = 1) +
  labs(title = "Good Bridges over a period under various authoorities",
       x ="",
       y = "Good Bridges %",
       color = "Responsible Authority") +
  scale_y_continuous(labels = percent_format())
```

```{r}
maryland_bridges %>% 
  filter(yr_built >= 1990) %>% 
  group_by(traffic_category) %>% 
  summarise(total = n(),
            pct_good = mean(bridge_condition == "Good"))
```

### Lets make a map

```{r}

maryland_bridges %>% 
  ggplot(aes(long, lat, color = responsibility)) +
  geom_point() +
  borders("state", regions = "Maryland") +
  theme_void() +
  coord_map()
  
```

```{r}
maryland_bridges %>% 
  ggplot(aes(long, lat, color = traffic_category)) +
  geom_point() +
  borders("state", regions = "Maryland") +
  theme_void() +
  coord_map()
```

```{r}

maryland_bridges %>% 
  ggplot(aes(long, lat, color = county)) +
  geom_point() +
  borders("state", regions = "Maryland") +
  theme_void() +
  coord_map()
```

```{r}

```

